services:
  - type: web
    name: mansooour
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn real_estate_platform.wsgi
    envVars:
      - key: CLOUD_NAME
        value: dvptglfs2
      - key: API_KEY
        value: 997257163374881
      - key: API_SECRET
        value: u5XPED3CQa2gd7PyHuEaw7BFsbY

