services:
  - type: web
    name: mansour-web
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py makemigrations
      python manage.py migrate
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: mansoour.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
