services:
  - type: web
    name: real-estate-platform
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --no-input
    startCommand: gunicorn real_estate_platform.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: real_estate_platform.settings
      - key: PYTHON_VERSION
        value: 3.11
