services:
  - type: web
    name: mansooour
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn real_estate_platform.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: real_estate_platform.settings
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: mansooour.onrender.com
