# Generated by Django 5.1.7 on 2025-04-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال'),
        ),
    ]
