# Generated by Django 5.1.7 on 2025-04-05 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_property_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequest',
            name='image',
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='request_type',
            field=models.CharField(choices=[('buy', 'شراء'), ('sell', 'بيع'), ('rent_out', 'تأجير'), ('rent', 'استئجار')], max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='request_images/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.customerrequest')),
            ],
        ),
    ]
