# Generated by Django 5.1.7 on 2025-04-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('land', 'أرض'), ('building', 'عمارة'), ('townhouse', 'تاون هاوس'), ('floor', 'دور')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('land', 'أرض'), ('building', 'عمارة'), ('townhouse', 'تاون هاوس'), ('floor', 'دور')], max_length=20),
        ),
    ]
