# Generated by Django 5.1.7 on 2025-04-08 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customerrequestimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('reserved', 'محجوز'), ('executed', 'تم التنفيذ')], default='open', max_length=10),
        ),
    ]
