# Generated by Django 5.1.7 on 2025-04-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customerrequest_reserved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'متاح'), ('reserved', 'محجوز'), ('executed', 'تم التنفيذ')], default='available', max_length=10),
        ),
    ]
