# Generated by Django 5.1.7 on 2025-04-30 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_properties', to=settings.AUTH_USER_MODEL, verbose_name='تم التنفيذ بواسطة'),
        ),
        migrations.AddField(
            model_name='property',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_properties', to=settings.AUTH_USER_MODEL, verbose_name='تم الحجز بواسطة'),
        ),
    ]
