# Generated by Django 5.1.7 on 2025-04-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_property_executed_by_property_reserved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التنفيذ'),
        ),
        migrations.AddField(
            model_name='property',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الحجز'),
        ),
    ]
