# Generated by Django 5.1.7 on 2025-04-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_property_executed_at_property_reserved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('land', 'أرض'), ('building', 'عمارة'), ('townhouse', 'تاون هاوس'), ('floor', 'دور'), ('palace', 'قصر'), ('chalet', 'استراحة'), ('farm', 'مزرعة')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('land', 'أرض'), ('building', 'عمارة'), ('townhouse', 'تاون هاوس'), ('floor', 'دور'), ('palace', 'قصر'), ('chalet', 'استراحة'), ('farm', 'مزرعة')], max_length=20),
        ),
    ]
